import {App} from 'vue'
import {
    AddressEdit,
    AddressList,
    Area,
    Button,
    Card,
    Cell,
    CellGroup,
    Checkbox,
    CheckboxGroup,
    Circle,
    Col,
    Collapse,
    CollapseItem,
    ContactCard,
    ContactEdit,
    ContactList,
    CouponCell,
    CouponList,
    DatetimePicker,
    Dialog,
    Field,
    Icon,
    ImagePreview,
    Lazyload,
    List,
    Loading,
    Locale,
    NavBar,
    NoticeBar,
    Notify,
    NumberKeyboard,
    Overlay,
    Pagination,
    PasswordInput,
    Picker,
    Popup,
    Progress,
    PullRefresh,
    Radio,
    RadioGroup,
    Rate,
    Row,
    Search,
    Slider,
    Step,
    Stepper,
    Steps,
    SubmitBar,
    Swipe,
    SwipeCell,
    SwipeItem,
    Switch,
    Tab,
    Tabbar,
    TabbarItem,
    Tabs,
    Tag,
    Toast,
    TreeSelect,
    Uploader,
    Image
} from 'vant'

export default function (app: App) {
    app.use(AddressEdit)
        .use(AddressList)
        .use(Area)
        .use(Button)
        .use(Card)
        .use(Cell)
        .use(CellGroup)
        .use(Checkbox)
        .use(CheckboxGroup)
        .use(Circle)
        .use(Col)
        .use(Collapse)
        .use(CollapseItem)
        .use(ContactCard)
        .use(ContactEdit)
        .use(ContactList)
        .use(CouponCell)
        .use(CouponList)
        .use(DatetimePicker)
        .use(Dialog)
        .use(Field)
        .use(Icon)
        .use(ImagePreview)
        .use(Lazyload)
        .use(List)
        .use(Loading)
        .use(Locale)
        .use(NavBar)
        .use(NoticeBar)
        .use(Notify)
        .use(NumberKeyboard)
        .use(Overlay)
        .use(Pagination)
        .use(PasswordInput)
        .use(Picker)
        .use(Popup)
        .use(Progress)
        .use(PullRefresh)
        .use(Radio)
        .use(RadioGroup)
        .use(Rate)
        .use(Row)
        .use(Search)
        .use(Slider)
        .use(Step)
        .use(Stepper)
        .use(Steps)
        .use(SubmitBar)
        .use(Swipe)
        .use(SwipeCell)
        .use(SwipeItem)
        .use(Switch)
        .use(Tab)
        .use(Tabbar)
        .use(TabbarItem)
        .use(Tabs)
        .use(Tag)
        .use(Toast)
        .use(TreeSelect)
        .use(Uploader)
        .use(Image)
}